Allow parsing incident numbers from repo URLs
These repo URLs are present via `OS_TEST_REPOS` which the code already
looks at but runs into the following error when trying to parse them:

```
ValueError: invalid literal for int() with base 10: '1.2:'
```

This is because the incident number is the 8th element in this URL but the
code expects it to be the 6th element. This change avoids this limitation
by using a regex instead of hard coding the index within the URL. The old
handling is also still in place as a fallback as I'm not sure what kind of
data it is supposed to match against.

Related ticket: https://progress.opensuse.org/issues/194579